apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
spec:
  containers:
    - name: app
      image: alpine:3.20
      command: ["sh","-c","id && sleep 3600"]
      securityContext:
        runAsUser: 0
