apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-03
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: alpine:3.20
      command: ["sh","-c","id && sleep 3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 10002
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
